# Generated by Django 4.0.3 on 2022-06-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(default='', max_length=200)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
    ]
