# Generated by Django 4.0.3 on 2022-06-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('book_type', models.CharField(default=None, max_length=50)),
                ('is_issued', models.BooleanField(default=True)),
            ],
        ),
    ]
